<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-04T14:35:07 IST" name="Suite" finished-at="2023-08-04T14:36:41 IST" duration-ms="94090">
    <groups>
    </groups>
    <test started-at="2023-08-04T14:35:07 IST" name="Test" finished-at="2023-08-04T14:36:41 IST" duration-ms="94090">
      <class name="TestCases.VerifyAddToCart">
        <test-method is-config="true" signature="launchBrowserandURL()[pri:0, instance:TestCases.VerifyAddToCart@22555ebf]" started-at="2023-08-04T14:35:51 IST" name="launchBrowserandURL" finished-at="2023-08-04T14:36:03 IST" duration-ms="12607" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowserandURL -->
        <test-method signature="CartTest()[pri:0, instance:TestCases.VerifyAddToCart@22555ebf]" started-at="2023-08-04T14:36:03 IST" name="CartTest" finished-at="2023-08-04T14:36:07 IST" duration-ms="3122" status="FAIL">
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[empty String]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: empty String
at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
at java.base/java.lang.Double.parseDouble(Double.java:651)
at TestCases.VerifyAddToCart.CartTest(VerifyAddToCart.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CartTest -->
      </class> <!-- TestCases.VerifyAddToCart -->
      <class name="TestCases.VerifyHeader">
        <test-method is-config="true" signature="launchBrowserandURL()[pri:0, instance:TestCases.VerifyHeader@45752059]" started-at="2023-08-04T14:36:07 IST" name="launchBrowserandURL" finished-at="2023-08-04T14:36:19 IST" duration-ms="12771" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowserandURL -->
        <test-method signature="VerifyDesktopHeader()[pri:0, instance:TestCases.VerifyHeader@45752059]" started-at="2023-08-04T14:36:19 IST" name="VerifyDesktopHeader" finished-at="2023-08-04T14:36:41 IST" duration-ms="21314" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyDesktopHeader -->
      </class> <!-- TestCases.VerifyHeader -->
      <class name="TestCases.VerifyRegisterAndLogin">
        <test-method is-config="true" signature="launchBrowserandURL()[pri:0, instance:TestCases.VerifyRegisterAndLogin@3270d194]" started-at="2023-08-04T14:35:07 IST" name="launchBrowserandURL" finished-at="2023-08-04T14:35:30 IST" duration-ms="23648" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowserandURL -->
        <test-method signature="VerifyValidRegister()[pri:0, instance:TestCases.VerifyRegisterAndLogin@3270d194]" started-at="2023-08-04T14:35:30 IST" name="VerifyValidRegister" finished-at="2023-08-04T14:35:42 IST" duration-ms="11536" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyValidRegister -->
        <test-method is-config="true" signature="launchBrowserandURL()[pri:0, instance:TestCases.VerifyRegisterAndLogin@3270d194]" started-at="2023-08-04T14:35:42 IST" name="launchBrowserandURL" finished-at="2023-08-04T14:35:46 IST" duration-ms="4533" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowserandURL -->
        <test-method signature="ValidLogin()[pri:1, instance:TestCases.VerifyRegisterAndLogin@3270d194]" started-at="2023-08-04T14:35:46 IST" name="ValidLogin" finished-at="2023-08-04T14:35:51 IST" duration-ms="4481" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
valid Error Text not showing expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found [Warning: No match for E-Mail Address and/or Password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
valid Error Text not showing expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found [Warning: No match for E-Mail Address and/or Password.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at Resources.commonmethod.verifyAssertions(commonmethod.java:31)
at TestCases.VerifyRegisterAndLogin.ValidLogin(VerifyRegisterAndLogin.java:117)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidLogin -->
      </class> <!-- TestCases.VerifyRegisterAndLogin -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
