<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-16T13:46:57 IST" name="Default suite" finished-at="2023-12-16T13:47:35 IST" duration-ms="38149">
    <groups>
    </groups>
    <test started-at="2023-12-16T13:46:57 IST" name="Default test" finished-at="2023-12-16T13:47:35 IST" duration-ms="38149">
      <class name="TestCases.VerifyRegisterAndLogin">
        <test-method is-config="true" signature="launchBrowserandURL()[pri:0, instance:TestCases.VerifyRegisterAndLogin@10e31a9a]" started-at="2023-12-16T13:46:57 IST" name="launchBrowserandURL" finished-at="2023-12-16T13:47:21 IST" duration-ms="24149" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowserandURL -->
        <test-method signature="VerifyValidRegister()[pri:0, instance:TestCases.VerifyRegisterAndLogin@10e31a9a]" started-at="2023-12-16T13:47:21 IST" name="VerifyValidRegister" finished-at="2023-12-16T13:47:27 IST" duration-ms="6046" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyValidRegister -->
        <test-method is-config="true" signature="launchBrowserandURL()[pri:0, instance:TestCases.VerifyRegisterAndLogin@10e31a9a]" started-at="2023-12-16T13:47:27 IST" name="launchBrowserandURL" finished-at="2023-12-16T13:47:31 IST" duration-ms="4370" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowserandURL -->
        <test-method signature="ValidLogin()[pri:1, instance:TestCases.VerifyRegisterAndLogin@10e31a9a]" started-at="2023-12-16T13:47:31 IST" name="ValidLogin" finished-at="2023-12-16T13:47:35 IST" duration-ms="3513" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
valid Error Text not showing expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found [Warning: No match for E-Mail Address and/or Password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
valid Error Text not showing expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found [Warning: No match for E-Mail Address and/or Password.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at Resources.commonmethod.verifyAssertions(commonmethod.java:31)
at TestCases.VerifyRegisterAndLogin.ValidLogin(VerifyRegisterAndLogin.java:117)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidLogin -->
      </class> <!-- TestCases.VerifyRegisterAndLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
